version: '3.7'
services:
    postgres_db:
        env_file:
         - .env
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=${PGUSER}
          - POSTGRES_PASSWORD=${PGPASSWORD}
        ports:
          - 5432:5432
        volumes: 
          # copy the sql script to create tables
          - ./sql_scripts/db.sql:/docker-entrypoint-initdb.d/db.sql  
        networks:
          - app-network 
    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - "8080:80"
        environment:
              PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
              PGADMIN_DEFAULT_PASSWORD: admin
        networks:
            - app-network
            
    cache:
        image: redis:7-alpine
        restart: always
        ports:
          - 6379:6379       
    nodeapp:
        build: . 
        restart: always
        ports:
          - 8080:8080
        env_file:
         - .env
        depends_on:
          - postgres_db
          - cache

networks:
  app-network:
    driver: bridge
