version: '3.7'
services:
    postgres_db:
        env_file:
            - .env
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: ${PGDATABASE}
            POSTGRES_USER: ${PGUSER}
            POSTGRES_PASSWORD: ${PGPASSWORD}
        ports:
            - 5432:5432
        volumes: 
            # copy the sql script to create tables
            - ./SQL/SAM_storage.sql:/docker-entrypoint-initdb.d/SAM_storage.sql
    cache:
            image: redis:7-alpine
            restart: always
            env_file:
                - .env
            ports:
                - ${REDIS_PORT}:6379
    nodeapp:
                build: . 
                restart: always
                ports:
                    - 8080:8080
                env_file:
                    - .env
                volumes:
                    - ${LOCAL_DATASET}:/usr/src/images
                depends_on:
                    - postgres_db
                    - cache