version: '3.7'
services:
    dbpg:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - 5432:5432
        volumes: 
          # copy the sql script to create tables
          - ./sql_scripts/db.sql:/docker-entrypoint-initdb.d/db.sql   
    cache:
        image: redis:7-alpine
        restart: always
        ports:
          - 6379:6379       
    nodeapp:
        build: . 
        restart: always
        ports:
          - 8080:8080
        env_file:
          - .env
        depends_on:
          - dbpg 
          - cache
